Repository hmcts/document-management-store-app, pull requests merged in 2019-04, with the labels that each got.

#285 Add AppInsight library and config
  lib/AI-Agent.xml
  lib/applicationinsights-agent-2.0.2.jar
  web.config
Labels: ns:dm-store-pr-285

#299 switch idam_api_url to SIDAM
  infrastructure/demo.tfvars
Labels: ns:dm-store-pr-299

#298 Scale out to 4 instance on prod
  infrastructure/prod.tfvars
  infrastructure/sprod.tfvars
Labels: ns:dm-store-pr-298

#300 introduced method level instrumentation support config
  application/lib/AI-Agent.xml
Labels: ns:dm-store-pr-300

#301 Instrumentation with ai agent logs
  lib/AI-Agent.xml
Labels: ns:dm-store-pr-301

#305 Instrumentation with ai agent logs
  lib/AI-Agent.xml
Labels: ns:dm-store-pr-305

#306 corrected accidentally pasted text
  lib/AI-Agent.xml
Labels: ns:dm-store-pr-306

#307 added instrumentation support for RequestStatusLoggingFilter
  lib/AI-Agent.xml
Labels: ns:dm-store-pr-307

#308 Rdm 4520 dm store performance fix
  .gitignore
  application/src/main/java/uk/gov/hmcts/dm/config/DmStoreAppInsightsConfig.java
Labels: ns:dm-store-pr-308

#302 change idam_api_url to SIDAM
  infrastructure/sprod.tfvars
Labels: ns:dm-store-pr-302

#310 Switch SIDAM
  infrastructure/demo.tfvars
Labels: ns:dm-store-pr-310

#311 fix health checker
  Dockerfile
Labels: ns:dm-store-pr-311
