Repository hmcts/document-management-store-app, pull requests merged in 2019-07, with the labels that each got.

#337 Updated the OWASP Library
  application/build.gradle
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store-pr-337

#338 Due to upgrading the Postgres JDBC Driver, the ssl=true needed to be …
  infrastructure/main.tf
Labels: ns:dm-store-pr-338

#343 bump OWASP
  build.gradle
Labels: ns:dm-store-pr-343
