Repository hmcts/document-management-store-app, pull requests merged in 2019-09, with the labels that each got.

#354 switch back to CCD shared infrastructure
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  infrastructure/variables.tf
Labels: ns:dm-store-pr-354

#355 update postgres terraform vars
  infrastructure/main.tf
Labels: ns:dm-store-pr-355

#356 EM-1963: Add rtf and csv files to whitelisted documents
  application/src/main/resources/application.yaml
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/prod.tfvars
Labels: ns:dm-store-pr-356

#362 remove redundant properties after spring 2.0 upgrade
  application/src/main/resources/application.yaml
  application/src/test/resources/application-local.yaml
  charts/dm-store/values.yaml
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/perftest.tfvars
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/variables.tf
Labels: ns:dm-store-pr-362
