Repository hmcts/document-management-store-app, pull requests merged in 2019-12, with the labels that each got.

#464 Remove s2s config
  application/src/main/resources/application.yaml
  application/src/main/resources/bootstrap.yaml
  charts/dm-store/Chart.yaml
  charts/dm-store/values.preview.template.yaml
  charts/dm-store/values.yaml
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/perftest.tfvars
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/variables.tf
Labels: ns:dm-store-pr-464

#467 Add jaxb runtime for in-cluster tests
  functionalTests/build.gradle
  functionalTests/src/functionalTest/groovy/uk/gov/hmcts/dm/functional/CreateDocumentIT.groovy
  functionalTests/src/functionalTest/groovy/uk/gov/hmcts/dm/functional/ErrorPageIT.groovy
  functionalTests/src/functionalTest/groovy/uk/gov/hmcts/dm/functional/ReadDocumentIT.groovy
  smokeTests/build.gradle
  smokeTests/src/smokeTest/groovy/uk/gov/hmcts/dm/smoke/MappingUrlIT.groovy
Labels: ns:dm-store-pr-467

#475 se.patrikerdes.use-latest-versions to 0.2.13
  application/build.gradle
Labels: ns:dm-store-pr-475
