Repository hmcts/document-management-store-app, pull requests merged in 2019-06, with the labels that each got.

#332 Bump spring boot to 1.5.21
  application/build.gradle
Labels: ns:dm-store-pr-332

#331 Added ethos repl service to the whitelist
  application/build.gradle
  charts/dm-store/values.yaml
  infrastructure/variables.tf
Labels: ns:dm-store-pr-331

#333 Use formal IDAM api URL for ITHC and Perftest
  infrastructure/ithc.tfvars
  infrastructure/perftest.tfvars
Labels: ns:dm-store-pr-333
