Repository hmcts/document-management-store-app, pull requests merged in 2020-10, with the labels that each got.

#785 Updated owasp version
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-785

#786 Updated azurerm details
  infrastructure/.terraform-version
  infrastructure/variables.tf
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-786

#787 Updated terraform details
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/versions.tf
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-787

#788 Updated bot config
  .github/renovate.json
  .github/stale.yml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-788

#783 introducing 3seconds sleep on api calls to check if it helps
  Jenkinsfile_nightly
  audit.json
  build.gradle
  config/owasp/dependency-check-suppressions.xml
  security.sh
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/CreateDocumentIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/ReadDocumentIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/SearchDocumentIT.groovy
  src/main/java/uk/gov/hmcts/dm/config/AliasWebConfig.java
  src/main/java/uk/gov/hmcts/dm/controller/WelcomeController.java
  src/smokeTest/groovy/uk/gov/hmcts/dm/smoke/SmokeTest.java
  src/test/java/uk/gov/hmcts/dm/controller/WelcomeControllerTest.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-783

#792 Updated bot config
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/stale.yml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-792
