Repository hmcts/document-management-store-app, pull requests merged in 2020-06, with the labels that each got.

#578 Update spring 2 2
  build.gradle
  charts/dm-store/Chart.yaml
  gradle/wrapper/gradle-wrapper.properties
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/UpdateDocumentIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/utilities/FileUtils.groovy
  src/main/java/uk/gov/hmcts/dm/DmApp.java
  src/main/java/uk/gov/hmcts/dm/commandobject/UploadDocumentsCommand.java
  src/main/java/uk/gov/hmcts/dm/config/AddMediaTypeSupportConfiguration.java
  src/main/java/uk/gov/hmcts/dm/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/dm/config/WebConfig.java
  src/main/java/uk/gov/hmcts/dm/controller/StoredDocumentAuditController.java
  src/main/java/uk/gov/hmcts/dm/controller/StoredDocumentSearchController.java
  src/main/java/uk/gov/hmcts/dm/errorhandler/ApiErrorAttributes.java
  src/main/java/uk/gov/hmcts/dm/errorhandler/ApiErrorController.java
  src/main/java/uk/gov/hmcts/dm/errorhandler/ExceptionStatusCodeAndMessageResolver.java
  src/main/java/uk/gov/hmcts/dm/hateos/DocumentContentVersionHalResource.java
  src/main/java/uk/gov/hmcts/dm/hateos/FolderHalResource.java
  src/main/java/uk/gov/hmcts/dm/hateos/HalResource.java
  src/main/java/uk/gov/hmcts/dm/hateos/StoredDocumentAuditEntryHalResource.java
  src/main/java/uk/gov/hmcts/dm/hateos/StoredDocumentHalResource.java
  src/main/java/uk/gov/hmcts/dm/hateos/StoredDocumentHalResourceCollection.java
  src/test/java/uk/gov/hmcts/dm/controller/StoredDocumentSearchControllerTests.java
  src/test/java/uk/gov/hmcts/dm/errorhandler/ExceptionStatusCodeAndMessageResolverTest.java
  src/test/java/uk/gov/hmcts/dm/hateos/DocumentContentVersionHalResourceTest.java
  src/test/java/uk/gov/hmcts/dm/service/SearchServiceTests.java
Labels: ns:dm-store, rel:dm-store-pr-578

#590 Remove requirements.yaml from chart and add renovate
  .github/renovate.json
  charts/dm-store/Chart.yaml
  charts/dm-store/requirements.yaml
Labels: ns:dm-store, rel:dm-store-pr-590

#622 Run del ttl steps in asynchronously
  src/main/java/uk/gov/hmcts/dm/config/batch/BatchConfiguration.java
Labels: ns:dm-store, rel:dm-store-pr-622

#591 Added in changes to update metadata
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/ReadDocumentIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/UpdateDocumentIT.groovy
  src/main/java/uk/gov/hmcts/dm/commandobject/UpdateDocumentCommand.java
  src/main/java/uk/gov/hmcts/dm/service/StoredDocumentService.java
Labels: ns:dm-store, rel:dm-store-pr-591

#652 server.use-forward-headers deprecated in springboot 2.2
  src/main/resources/application.yaml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-652

#653 Test for P1 RDM-8742
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/CreateDocumentIT.groovy
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-653

#708 Added @Pending to tests that are toggled off - Serenity Reporting
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/MetadataMigrationIT.groovy
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-708
