Repository hmcts/document-management-store-app, pull requests merged in 2020-11, with the labels that each got.

#793 Ta 87 provider Verification test for Divorce
  Jenkinsfile_CNP
  README.md
  build.gradle
  config/owasp/dependency-check-suppressions.xml
  src/contractTest/java/uk/gov/hmcts/dm/controller/DocumentStoreProviderTest.java
  src/contractTest/java/uk/gov/hmcts/dm/controller/StoreDocumentControllerTestConfiguration.java
  src/contractTest/resources/application.yaml
  src/test/resources/application-local.yaml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-793

#796 Updated PACT_BROKER_URL
  Jenkinsfile_CNP
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-796

#797 Updated terraform version
  infrastructure/.terraform-version
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-797

#795 EM-3229 DM-Store: Update functional and smoke test cases to generate …
  build.gradle
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/AddContentVersionIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/BaseIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/CreateDocumentIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/DeleteDocumentIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/ErrorPageIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/HealthUrlIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/MetadataMigrationIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/MultiMediaUploadIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/ReadContentVersionIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/ReadDocumentIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/SearchDocumentIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/UpdateDocumentIT.groovy
  src/functionalTest/java/uk/gov/hmcts/dm/FunctionalTestContextConfiguration.java
  src/smokeTest/groovy/uk/gov/hmcts/dm/smoke/BaseIT.groovy
  src/smokeTest/groovy/uk/gov/hmcts/dm/smoke/HealthUrlIT.groovy
  src/smokeTest/groovy/uk/gov/hmcts/dm/smoke/MappingUrlIT.groovy
  src/smokeTest/groovy/uk/gov/hmcts/dm/smoke/SmokeTest.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-795

#798 Removed unused mi variable
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-798

#799 Updated azurerm version
  infrastructure/state.tf
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-799

#800 EM-3237 - DM API : Investigate DM api failing nightly build jobs
  Jenkinsfile_nightly
  build.gradle
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/nightly/pipeline/CreateDocumentIT.groovy
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-800
