Repository hmcts/document-management-store-app, pull requests merged in 2020-04, with the labels that each got.

#566 Deploys required Azure Media Service infra
  application/build.gradle
  config/owasp/dependency-check-suppressions.xml
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/variables.tf
Labels: DO NOT MERGE, ns:dm-store, rel:dm-store-pr-566

#568 Upgrade to terraform 0.12
  .gitignore
  .terraform-version
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/perftest.tfvars
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/variables.tf
Labels: ns:dm-store, rel:dm-store-pr-568

#569 add man id demo
  infrastructure/demo.tfvars
Labels: ns:dm-store, rel:dm-store-pr-569
