Repository hmcts/document-management-store-app, pull requests merged in 2020-12, with the labels that each got.

#803 EM-3261 - DM-Store: Add retry logic for failing functional test cases
  build.gradle
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/AddContentVersionIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/DeleteDocumentIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/ErrorPageIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/HealthUrlIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/MetadataMigrationIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/MultiMediaUploadIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/ReadContentVersionIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/ReadDocumentIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/SearchDocumentIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/UpdateDocumentIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/nightly/pipeline/CreateDocumentIT.groovy
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-803

#804 Suppressed Vulnerability
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-804

#807 EM-3290 - Dm-store API - Update local environment setup instructions …
  .dependabot/config.yml
  .github/renovate.json
  .github/stale.yml
  README.md
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-807

#814 Resolved vulnerability
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-814

#815 Resolved vulnerability
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-815
