Repository hmcts/document-management-store-app, pull requests merged in 2021-01, with the labels that each got.

#827 whitelist new divorce service, nfdiv_cos
  src/main/resources/application.yaml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-827

#836 Added ingressHost
  charts/dm-store/Chart.yaml
  charts/dm-store/values.yaml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-836

#849 EM-3432 - Dm-store API - Upgrade serenity version
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-849

#851 Em 3363 resolve cve 2
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-851
