Repository hmcts/document-management-store-app, pull requests merged in 2021-03, with the labels that each got.

#879 Resolved CVE-2021-22112
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-879

#887 Resolved CVE-2021-25122, CVE-2021-25329
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-887

#801 trim roles to avoid missing valid roles due to spaces
  README.md
  build.gradle
  config/pmd/ruleset.xml
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/BaseIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/ErrorPageIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/MetadataMigrationIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/ReadDocumentIT.groovy
  src/functionalTest/java/uk/gov/hmcts/dm/functional/AuthTokenProvider.java
  src/main/java/uk/gov/hmcts/dm/config/batch/MetadataMigrationConfiguration.java
  src/main/java/uk/gov/hmcts/dm/domain/DocumentContentVersion.java
  src/main/java/uk/gov/hmcts/dm/errorhandler/ApiErrorAttributes.java
  src/main/java/uk/gov/hmcts/dm/security/PermissionEvaluatorImpl.java
  src/main/java/uk/gov/hmcts/dm/security/domain/DomainPermissionEvaluator.java
  src/main/java/uk/gov/hmcts/dm/service/SecurityUtilService.java
  src/test/java/uk/gov/hmcts/dm/actuate/info/DmBuildInfoTest.java
  src/test/java/uk/gov/hmcts/dm/componenttests/sugar/RestActions.java
  src/test/java/uk/gov/hmcts/dm/endtoend/VersionTest.java
  src/test/java/uk/gov/hmcts/dm/errorhandler/ExceptionStatusCodeAndMessageResolverTest.java
  src/test/java/uk/gov/hmcts/dm/security/domain/DomainPermissionEvaluatorTests.java
  src/test/java/uk/gov/hmcts/dm/service/BlobStorageWriteServiceTest.java
  src/test/java/uk/gov/hmcts/dm/service/thumbnail/DocumentThumbnailServiceTest.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-801

#900 update SKU to alleviate AAT pressure
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-900

#901 add in core number
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-901

#902 Reverted tomcat version
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-902

#905 Pact verification publish fix
  Jenkinsfile_CNP
  build.gradle
  src/contractTest/java/uk/gov/hmcts/dm/controller/DocumentStoreProviderTest.java
  src/contractTest/resources/application.yaml
  src/contractTest/resources/logback-test.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-905

#903 EM-3652 - Dm-store API - Add functional tests for DocumentContentVers…
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/ReadContentVersionIT.groovy
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-903

#904 EM-3656 - Dm-store API - Add functional tests for DocumentThumbnailCo…
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/CreateDocumentIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/ReadThumbnailIT.groovy
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-904

#906 EM-3660 - Dm-store API - Add functional tests for StoredDocumentContr…
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/ReadDocumentIT.groovy
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-906

#913 EM-3675 - Dm-store API - Add functional tests for StoredDocumentUpdat…
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/UpdateDocumentIT.groovy
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-913
