Repository hmcts/document-management-store-app, pull requests merged in 2021-04, with the labels that each got.

#919 Resolved CVE's
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-919

#920 EM-3695 -Dm-store API - Fix serenity report issue
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-920

#927 EM-3716 - Dm-store API - Update Jenkins file to generate all reports …
  Jenkinsfile_CNP
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-927
