Repository hmcts/document-management-store-app, pull requests merged in 2021-02, with the labels that each got.

#864 Em 3485 - Fix for Jenkins build failures
  Jenkinsfile_nightly
  build.gradle
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/CreateDocumentIT.groovy
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-864

#870 Resolved CVE-2021-21290
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-870

#871 EM-3525- Dm-store API - Suppress nightly jobs dependency vulnerabilit…
  audit.json
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-871

#876 Updated terraform version
  infrastructure/.terraform-version
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-876
