Repository hmcts/document-management-store-app, pull requests merged in 2021-06, with the labels that each got.

#998 Fixed CVE
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-998

#1007 Updated jitpack libraries reference
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1007

#1009 Enable Swagger documentation endpoint
  README.md
  build.gradle
  src/main/java/uk/gov/hmcts/dm/config/SwaggerConfiguration.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1009

#1013 Fixed resource leak issue
  src/main/java/uk/gov/hmcts/dm/actuate/info/DmBuildInfo.java
  src/test/java/uk/gov/hmcts/dm/actuate/info/DmBuildInfoTest.java
  src/test/resources/META-INF/build-info-with-build-no.properties
  src/test/resources/META-INF/build-info.properties
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1013

#1012 Fixing nightly build
  audit.json
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1012

#1014 replacing \\ with \
  audit.json
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1014

#1015 Fixed log forging issue
  src/main/java/uk/gov/hmcts/dm/security/domain/DomainPermissionEvaluator.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1015

#1017 Fixed resource leak issue
  src/main/java/uk/gov/hmcts/dm/config/batch/UpdateDocumentMetaDataTasklet.java
  src/main/java/uk/gov/hmcts/dm/dialect/ByteWrappingBlobType.java
  src/main/java/uk/gov/hmcts/dm/service/DocumentContentVersionService.java
  src/test/java/uk/gov/hmcts/dm/dialect/ByteWrappingBlobTypeTests.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1017

#977 Upgraded SpringBoot 2.4.5
  Jenkinsfile_CNP
  build.gradle
  charts/dm-store/Chart.yaml
  charts/dm-store/values.preview.template.yaml
  charts/dm-store/values.yaml
  config/owasp/dependency-check-suppressions.xml
  lib/AI-Agent.xml
  src/main/java/uk/gov/hmcts/dm/exception/CantCreateBlobException.java
  src/main/java/uk/gov/hmcts/dm/service/BlobCreator.java
  src/main/resources/application.yaml
  src/main/resources/bootstrap.yaml
  src/smokeTest/groovy/uk/gov/hmcts/dm/smoke/MappingUrlIT.groovy
  src/test/java/uk/gov/hmcts/dm/controller/FolderControllerTests.java
  src/test/java/uk/gov/hmcts/dm/service/BlobCreatorTests.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-977

#1027 Updated hmcts java library
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1027

#1030 Updated DB details
  infrastructure/main.tf
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1030
