Repository hmcts/document-management-store-app, pull requests merged in 2021-11, with the labels that each got.

#1171 EM-4110: remove old un-used ase tf code
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/variables.tf
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1171

#1172 EM-4112: fix spring cve
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1172

#1170 Fix for download exception
  src/main/java/uk/gov/hmcts/dm/service/BlobStorageReadService.java
  src/test/java/uk/gov/hmcts/dm/service/BlobStorageReadServiceTest.java
  src/test/java/uk/gov/hmcts/dm/service/BlobStorageWriteServiceTest.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1170

#1181 Updated tf version
  infrastructure/.terraform-version
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/output.tf
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/state.tf
  infrastructure/variables.tf
  infrastructure/versions.tf
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1181

#1185 Added in default values for empty variables
  infrastructure/variables.tf
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1185

#1180 Added v11 db details
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1180

#1184 Disabled metadatamigration as default
  Jenkinsfile_CNP
  charts/dm-store/values.preview.template.yaml
  src/contractTest/resources/application.yaml
  src/main/resources/application.yaml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1184

#1174 Sbupgrade
  build.gradle
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/ErrorPageIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/HealthUrlIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/ReadDocumentIT.groovy
  src/functionalTest/resources/application.yml
  src/smokeTest/groovy/uk/gov/hmcts/dm/smoke/HealthUrlIT.groovy
  src/smokeTest/groovy/uk/gov/hmcts/dm/smoke/MappingUrlIT.groovy
  src/smokeTest/groovy/uk/gov/hmcts/dm/smoke/SmokeTest.java
  src/smokeTest/resources/application-smoke-test.yaml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1174

#1206 Added in more logs for 500 error status response
  src/main/java/uk/gov/hmcts/dm/controller/StoredDocumentController.java
  src/main/java/uk/gov/hmcts/dm/hateos/StoredDocumentHalResource.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1206

#1207 Add in check for headers
  src/main/java/uk/gov/hmcts/dm/controller/StoredDocumentController.java
  src/main/java/uk/gov/hmcts/dm/hateos/StoredDocumentHalResource.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1207

#1211 Added in more logs for 500 error
  src/main/java/uk/gov/hmcts/dm/controller/StoredDocumentController.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1211
