Repository hmcts/document-management-store-app, pull requests merged in 2021-08, with the labels that each got.

#1068 Updated log level to info for migration job
  src/main/java/uk/gov/hmcts/dm/config/batch/UpdateDocumentMetaDataTasklet.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1068

#1076 Fix broken build pipeline
  Jenkinsfile_CNP
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1076

#1079 Resolved CVE
  build.gradle
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/MultiMediaUploadIT.groovy
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1079

#1091 EM-4024: fix terraform version
  infrastructure/state.tf
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1091
