Repository hmcts/document-management-store-app, pull requests merged in 2021-05, with the labels that each got.

#960 Copy AppInsightsKey reference
  infrastructure/main.tf
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-960

#961 Copy RpaAppInsightsKey reference
  infrastructure/main.tf
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-961

#962 Refer to RpaAppInsightsKey
  charts/dm-store/Chart.yaml
  charts/dm-store/values.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-962

#968 Whitelisted civil_service
  src/main/resources/application.yaml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-968

#976 Updated docker-compose-dependencies
  docker-compose-dev.yml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-976

#979 Suppressing same site cookie vulnerability
  audit.json
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-979

#986 Update build.gradle
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-986
