Repository hmcts/document-management-store-app, pull requests merged in 2022-06, with the labels that each got.

#1378 Resolved CVE
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1378

#1379 Updated the rule for Deletion of Documents
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  docker-compose-dev.yml
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/BaseIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/DeleteDocumentIT.groovy
  src/functionalTest/java/uk/gov/hmcts/dm/functional/AuthTokenProvider.java
  src/functionalTest/resources/application.yml
  src/main/java/uk/gov/hmcts/dm/security/domain/DomainPermissionEvaluator.java
  src/test/java/uk/gov/hmcts/dm/security/domain/DomainPermissionEvaluatorTests.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1379

#1380 Fix CVE-2022-22978, Update SpringSecurityConfiguration
  build.gradle
  src/main/java/uk/gov/hmcts/dm/config/security/SpringSecurityConfiguration.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1380

#1381 whitelist application/octet-stream
  src/contractTest/resources/application.yaml
  src/main/resources/application.yaml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1381

#1383 Setting TTL date for soft-deleted documents
  src/main/java/uk/gov/hmcts/dm/service/AuditedStoredDocumentOperationsService.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1383

#1386 Upgrade base java chart
  charts/dm-store/Chart.yaml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1386

#1387 Resolved migratePostgresDatabase error
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1387

#1388 Resolved batch related tables local setup issue
  README.md
  bin/create-batch-related-tables-postresql.sh
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1388

#1391 Disabled syncBranchesWithMaster
  Jenkinsfile_CNP
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1391
