Repository hmcts/document-management-store-app, pull requests merged in 2022-09, with the labels that each got.

#1420 Resolved CVE
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1420

#1421 Added in dependabot config
  .github/dependabot.yml
  .github/renovate.json
  .github/stale.yml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1421

#1434 Enable Multi architecture for evidence
  .dockerignore
  Dockerfile
  acb.tpl.yaml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1434

#1437 Merged bot prs in to one
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1437

#1447 Merged bot prs in to one
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1447

#1454 Use em-test-helper version 1.21.4
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1454

#1460 EM-4606 copy app-inisght connection string from RPA
  charts/dm-store/Chart.yaml
  charts/dm-store/values.yaml
  infrastructure/main.tf
Labels: ns:dm-store, prd:dm, add-or-update, rel:dm-store-pr-1460
