Repository hmcts/document-management-store-app, pull requests merged in 2022-05, with the labels that each got.

#1358 Updated README for swagger link
  README.md
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1358

#1294 DO NOT MERGE - LAU -199 Doucments-delete end-point
  src/contractTest/java/uk/gov/hmcts/dm/controller/DocumentStoreProviderTest.java
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/DeleteDocumentsIT.groovy
  src/main/java/uk/gov/hmcts/dm/commandobject/DeleteCaseDocumentsCommand.java
  src/main/java/uk/gov/hmcts/dm/controller/StoredDocumentDeleteController.java
  src/main/java/uk/gov/hmcts/dm/exception/InvalidRequestException.java
  src/main/java/uk/gov/hmcts/dm/repository/StoredDocumentRepository.java
  src/main/java/uk/gov/hmcts/dm/response/CaseDocumentsDeletionResults.java
  src/main/java/uk/gov/hmcts/dm/service/AuditedStoredDocumentOperationsService.java
  src/main/java/uk/gov/hmcts/dm/service/Constants.java
  src/main/java/uk/gov/hmcts/dm/service/SearchService.java
  src/main/java/uk/gov/hmcts/dm/utils/InputParamsVerifier.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/dm/controller/StoredDocumentDeleteControllerTests.java
  src/test/java/uk/gov/hmcts/dm/service/AuditedStoredDocumentOperationsServiceTests.java
  src/test/java/uk/gov/hmcts/dm/service/SearchServiceTests.java
  src/test/java/uk/gov/hmcts/dm/utils/InputParamsVerifierTest.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1294

#1361 Added in more logs to investigate CDAM issue
  src/main/java/uk/gov/hmcts/dm/controller/StoredDocumentController.java
  src/main/java/uk/gov/hmcts/dm/domain/StoredDocument.java
  src/main/java/uk/gov/hmcts/dm/hateos/DocumentContentVersionHalResource.java
  src/main/java/uk/gov/hmcts/dm/hateos/StoredDocumentAuditEntryHalResource.java
  src/main/java/uk/gov/hmcts/dm/hateos/StoredDocumentHalResource.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1361

#1364 Updated config for Renovate Bot
  .github/dependabot.yml
  .github/renovate.json
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1364

#1368 Disabled Fork for functional tests to resolve Nightly Build failures
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1368

#1363 Fix Nightly Build
  build.gradle
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/SearchDocumentIT.groovy
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1363

#1373 Removed dependabot config
  .github/dependabot.yml
  .github/stale.yml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1373

#1375 Added in unit test
  build.gradle
  src/main/java/uk/gov/hmcts/dm/controller/StoredDocumentUpdateController.java
  src/test/java/uk/gov/hmcts/dm/controller/StoredDocumentUpdateControllerTests.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1375

#1377 Revert "Added DB indexes"
  src/main/resources/db/changelog/db.changelog-diff-EM-4452-add_indexes.xml
  src/main/resources/db/changelog/db.changelog-master.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1377
