Repository hmcts/document-management-store-app, pull requests merged in 2022-03, with the labels that each got.

#1299 update postgres version to 11 for local setup
  build.gradle
  docker/database/Dockerfile
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1299

#1309 Fix for functional tests issue on PR build
  charts/dm-store/Chart.yaml
  charts/dm-store/values.preview.template.yaml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1309

#1313 Upgraded SpringBoot version to 2.6.4 and removed powermock libraries
  build.gradle
  src/contractTest/resources/application.yaml
  src/main/java/uk/gov/hmcts/dm/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/dm/config/security/SpringSecurityConfiguration.java
  src/main/java/uk/gov/hmcts/dm/controller/DocumentContentVersionController.java
  src/main/java/uk/gov/hmcts/dm/controller/DocumentThumbnailController.java
  src/main/java/uk/gov/hmcts/dm/controller/FolderController.java
  src/main/java/uk/gov/hmcts/dm/controller/StoredDocumentAuditController.java
  src/main/java/uk/gov/hmcts/dm/controller/StoredDocumentController.java
  src/main/java/uk/gov/hmcts/dm/controller/StoredDocumentDeleteController.java
  src/main/java/uk/gov/hmcts/dm/controller/StoredDocumentSearchController.java
  src/main/java/uk/gov/hmcts/dm/controller/StoredDocumentUpdateController.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/dm/controller/testing/TestControllerTest.java
  src/test/java/uk/gov/hmcts/dm/service/BlobStorageDeleteServiceTest.java
  src/test/java/uk/gov/hmcts/dm/service/BlobStorageReadServiceTest.java
  src/test/java/uk/gov/hmcts/dm/service/BlobStorageWriteServiceTest.java
  src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1313

#1320 Update liquibase lib
  build.gradle
  config/owasp/dependency-check-suppressions.xml
  liquibase.gradle
  src/contractTest/resources/application.yaml
  src/main/java/uk/gov/hmcts/dm/DmApp.java
  src/main/resources/application.yaml
  src/main/resources/liquibase.properties
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1320

#1321 Reverted com.github.hmcts.liquibase lib changes
  build.gradle
  config/owasp/dependency-check-suppressions.xml
  liquibase.gradle
  src/contractTest/resources/application.yaml
  src/main/java/uk/gov/hmcts/dm/DmApp.java
  src/main/resources/application.yaml
  src/main/resources/liquibase.properties
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1321

#1323 Update dependabot.yml
  .github/dependabot.yml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1323

#1330 Remove jackson-bom
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1330

#1333 Updated azurerm version
  infrastructure/state.tf
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1333
