Repository hmcts/document-management-store-app, pull requests merged in 2022-01, with the labels that each got.

#1245 Whitelist Employment Tribunal service
  src/main/resources/application.yaml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1245

#1248 Updated log4J version
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1248

#1254 DO NOT MERGE : Avoid reporting spurious 500 errors in AppInsights
  src/main/java/uk/gov/hmcts/dm/controller/StoredDocumentController.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1254

#1264 Ignored failing tests till further investigations
  src/test/java/uk/gov/hmcts/dm/endtoend/AuditTest.java
  src/test/java/uk/gov/hmcts/dm/endtoend/PermissionTest.java
  src/test/java/uk/gov/hmcts/dm/endtoend/SearchDocumentTest.java
  src/test/java/uk/gov/hmcts/dm/endtoend/ThumbnailTest.java
  src/test/java/uk/gov/hmcts/dm/endtoend/UploadDocumentTest.java
  src/test/java/uk/gov/hmcts/dm/endtoend/VersionTest.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1264

#1270 Fix for fortify issue
  src/main/java/uk/gov/hmcts/dm/service/SecurityUtilService.java
  src/main/java/uk/gov/hmcts/dm/utils/StringUtils.java
  src/test/java/uk/gov/hmcts/dm/utils/StringUtilsTests.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1270

#1271 Reverted failing tests changes
  src/test/java/uk/gov/hmcts/dm/endtoend/AuditTest.java
  src/test/java/uk/gov/hmcts/dm/endtoend/PermissionTest.java
  src/test/java/uk/gov/hmcts/dm/endtoend/SearchDocumentTest.java
  src/test/java/uk/gov/hmcts/dm/endtoend/ThumbnailTest.java
  src/test/java/uk/gov/hmcts/dm/endtoend/UploadDocumentTest.java
  src/test/java/uk/gov/hmcts/dm/endtoend/VersionTest.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1271
