Repository hmcts/document-management-store-app, pull requests merged in 2022-07, with the labels that each got.

#1396 Added in preconditions for 3 new indexes
  build.gradle
  src/main/resources/db/changelog/db.changelog-diff-EM-4484-add_indexes.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1396

#1400 LAU-466 Improve dm-store store delete document endpoint
  src/main/java/uk/gov/hmcts/dm/response/CaseDocumentsDeletionResults.java
  src/main/java/uk/gov/hmcts/dm/service/AuditedStoredDocumentOperationsService.java
  src/test/java/uk/gov/hmcts/dm/controller/StoredDocumentDeleteControllerTest.java
  src/test/java/uk/gov/hmcts/dm/service/AuditedStoredDocumentOperationsServiceTests.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1400

#1401 Updated springboot & lib version & removed redundant cve suppression.
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1401
