Repository hmcts/document-management-store-app, pull requests merged in 2022-11, with the labels that each got.

#1519 EM-4533 Add index
  src/main/resources/application.yaml
  src/main/resources/db/migration/V2__add_index_delete_expired-docs.sql
  src/main/resources/db/migration/V3__analyze.sql
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1519

#1524 Revert "EM-3001 add pdf encryption validation"
  src/main/java/uk/gov/hmcts/dm/service/FileContentVerifier.java
  src/test/java/uk/gov/hmcts/dm/service/FileContentVerifierTests.java
  src/test/resources/files/PasswordProtected.pdf
  src/test/resources/files/sample_encrypted.pdf
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1524

#1527 Em-4744 avoid CVE 2022 31692
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1527

#1530 EM-4755 remove deprecated methods
  src/main/java/uk/gov/hmcts/dm/service/BlobStorageReadService.java
  src/test/java/uk/gov/hmcts/dm/service/BlobStorageReadServiceTest.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1530

#1535 EM-4773 switch off SQL logs
  src/main/resources/application.yaml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1535

#1529 Removed probate from whitelist for non-prod envs
  charts/dm-store/Chart.yaml
  charts/dm-store/values.yaml
Labels: ns:dm-store, prd:dm, Do Not Merge, rel:dm-store-pr-1529

#1537 EM-4765 not log exception stack
  src/main/java/uk/gov/hmcts/dm/controller/StoredDocumentController.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1537

#1536 EM-4775: DM - to spin up dm-store locally
  docker-compose-dev.yml
  docker/database/Dockerfile
  docker/database/init-db.sh
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1536

#1539 EM-4765 not log exception stack
  build.gradle
  config/checkstyle/checkstyle.xml
  src/main/java/uk/gov/hmcts/dm/controller/DocumentContentVersionController.java
  src/main/java/uk/gov/hmcts/dm/controller/StoredDocumentController.java
  src/main/java/uk/gov/hmcts/dm/controller/StoredDocumentSearchController.java
  src/main/java/uk/gov/hmcts/dm/service/DocumentContentVersionModel.java
Labels: ns:dm-store, prd:dm, Do Not Merge, rel:dm-store-pr-1539

#1551 Resolve master build failure
  src/test/java/uk/gov/hmcts/dm/controller/StoredDocumentControllerTests.java
  src/test/java/uk/gov/hmcts/dm/service/FileContentVerifierTests.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1551

#1562 EM-4831 check container before create
  src/main/java/uk/gov/hmcts/dm/config/azure/AzureStorageConfiguration.java
  src/main/java/uk/gov/hmcts/dm/config/azure/MetaDataAzureStorageConfiguration.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1562

#1544 Em3065: Functional tests to verify large file uploads
  charts/dm-store/values.preview.template.yaml
  src/functionalTest/java/uk/gov/hmcts/dm/FunctionalTestContextConfiguration.java
  src/functionalTest/java/uk/gov/hmcts/dm/StorageTestConfiguration.java
  src/functionalTest/java/uk/gov/hmcts/dm/functional/BaseIT.java
  src/functionalTest/java/uk/gov/hmcts/dm/functional/LargeMultiMediaUploadIT.java
  src/functionalTest/java/uk/gov/hmcts/dm/functional/blob/BlobReader.java
  src/functionalTest/resources/application.yml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1544

#1571 EM-4846 avoid vulnerability
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1571
