Repository hmcts/document-management-store-app, pull requests merged in 2022-02, with the labels that each got.

#1273 DO NOT MERGE : Removed unused PostGres Blob related lines
  build.gradle
  src/contractTest/java/uk/gov/hmcts/dm/controller/DocumentStoreProviderTest.java
  src/contractTest/java/uk/gov/hmcts/dm/controller/StoreDocumentControllerTestConfiguration.java
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/AddContentVersionIT.groovy
  src/main/java/uk/gov/hmcts/dm/config/azure/AzureStorageConfiguration.java
  src/main/java/uk/gov/hmcts/dm/controller/DocumentContentVersionController.java
  src/main/java/uk/gov/hmcts/dm/controller/StoredDocumentController.java
  src/main/java/uk/gov/hmcts/dm/domain/DocumentContent.java
  src/main/java/uk/gov/hmcts/dm/domain/DocumentContentVersion.java
  src/main/java/uk/gov/hmcts/dm/repository/DocumentContentRepository.java
  src/main/java/uk/gov/hmcts/dm/repository/DocumentContentVersionRepository.java
  src/main/java/uk/gov/hmcts/dm/service/AuditedDocumentContentVersionOperationsService.java
  src/main/java/uk/gov/hmcts/dm/service/DocumentContentVersionService.java
  src/main/java/uk/gov/hmcts/dm/service/StoredDocumentService.java
  src/main/resources/application.yaml
  src/main/resources/db/changelog/db.changelog-diff-20220128-1655.xml
  src/main/resources/db/changelog/db.changelog-master.xml
  src/test/java/uk/gov/hmcts/dm/componenttests/ComponentTestBase.java
  src/test/java/uk/gov/hmcts/dm/componenttests/TestUtil.java
  src/test/java/uk/gov/hmcts/dm/controller/DocumentContentVersionControllerTest.java
  src/test/java/uk/gov/hmcts/dm/controller/DocumentThumbnailControllerTests.java
  src/test/java/uk/gov/hmcts/dm/controller/StoredDocumentControllerNoDeleteTests.java
  src/test/java/uk/gov/hmcts/dm/controller/StoredDocumentControllerTests.java
  src/test/java/uk/gov/hmcts/dm/endtoend/End2EndTestBase.java
  src/test/java/uk/gov/hmcts/dm/service/AuditedDocumentContentVersionOperationsServiceTests.java
  src/test/java/uk/gov/hmcts/dm/service/DocumentContentVersionServiceTests.java
  src/test/java/uk/gov/hmcts/dm/service/StoredDocumentServiceTests.java
  src/test/java/uk/gov/hmcts/dm/service/thumbnail/ImageThumbnailCreatorTest.java
  src/test/java/uk/gov/hmcts/dm/service/thumbnail/PdfThumbnailCreatorTest.java
  src/test/resources/application-local.yaml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1273

#1280 Fix db build issue
  build.gradle
  src/main/resources/db/changelog/db.changelog-diff-20220128-1655.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1280

#1281 Reverted domain changes to resolve db issue
  src/main/java/uk/gov/hmcts/dm/domain/DocumentContent.java
  src/main/java/uk/gov/hmcts/dm/domain/DocumentContentVersion.java
  src/main/resources/db/changelog/db.changelog-diff-20220128-1655.xml
  src/main/resources/db/changelog/db.changelog-master.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1281

#1288 Fix CVE's
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1288

#1290 Resolved CVE
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1290

#1289 Update helm chart
  charts/dm-store/Chart.yaml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1289

#1296 Resolved CVE
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1296
