Repository hmcts/document-management-store-app, pull requests merged in 2022-08, with the labels that each got.

#1402 Removed xui_webapp from whitelist
  src/contractTest/resources/application.yaml
  src/main/resources/application.yaml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1402

#1405 Resolved CVE
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1405

#1409 Updated the test urls to use https
  Jenkinsfile_CNP
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/AddContentVersionIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/BaseIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/CreateDocumentIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/DeleteDocumentIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/MultiMediaUploadIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/ReadContentVersionIT.groovy
  src/functionalTest/groovy/uk/gov/hmcts/dm/functional/ReadThumbnailIT.groovy
  src/functionalTest/resources/application.yml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1409

#1410 Resolved fortify preview secret issue
  charts/dm-store/Chart.yaml
  charts/dm-store/values.preview.template.yaml
  charts/dm-store/values.yaml
  src/main/resources/application.yaml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1410

#1407 Increased Prod DB size
  Jenkinsfile_CNP
  infrastructure/prod.tfvars
Labels: ns:dm-store, prd:dm, no-changes, rel:dm-store-pr-1407

#1412 Added in documentmetadata_value_idx index
  src/main/resources/db/changelog/db.changelog-diff-EM-4561-add_index.xml
  src/main/resources/db/changelog/db.changelog-master.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1412

#1415 Removed civil_service from whitelist
  src/main/resources/application.yaml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1415

#1413 Add backstage configuration file
  catalog-info.yaml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1413

#1419 Flyway migration on AAT & Prod
  build.gradle
  charts/dm-store/Chart.yaml
  charts/dm-store/values.preview.template.yaml
  charts/dm-store/values.yaml
  config/owasp/dependency-check-suppressions.xml
  docker-compose-dev.yml
  liquibase.gradle
  src/contractTest/resources/application.yaml
  src/main/java/uk/gov/hmcts/dm/DmApp.java
  src/main/java/uk/gov/hmcts/dm/config/FlywayConfiguration.java
  src/main/java/uk/gov/hmcts/dm/data/migration/FlywayNoOpStrategy.java
  src/main/java/uk/gov/hmcts/dm/data/migration/PendingMigrationScriptException.java
  src/main/resources/application.yaml
  src/main/resources/db/changelog/db.changelog-diff-20171005-1419.xml
  src/main/resources/db/changelog/db.changelog-diff-20171108-1409.xml
  src/main/resources/db/changelog/db.changelog-diff-20171122-1046.xml
  src/main/resources/db/changelog/db.changelog-diff-20171220-1242.xml
  src/main/resources/db/changelog/db.changelog-diff-20180116-1450.xml
  src/main/resources/db/changelog/db.changelog-diff-20180124-1546.xml
  src/main/resources/db/changelog/db.changelog-diff-20180129-1006.xml
  src/main/resources/db/changelog/db.changelog-diff-20180205-1547.xml
  src/main/resources/db/changelog/db.changelog-diff-20180205-1604.xml
  src/main/resources/db/changelog/db.changelog-diff-EM-2390-shedlock.xml
  src/main/resources/db/changelog/db.changelog-diff-EM-2542-clean-batch-tables.xml
  src/main/resources/db/changelog/db.changelog-diff-EM-4484-add_indexes.xml
  src/main/resources/db/changelog/db.changelog-diff-EM-4561-add_index.xml
  src/main/resources/db/changelog/db.changelog-diff-RDM-2828-migration-checksum.xml
  src/main/resources/db/changelog/db.changelog-diff-RDM-2828.xml
  src/main/resources/db/changelog/db.changelog-diff-RDM-2991-migration-audit.xml
  src/main/resources/db/changelog/db.changelog-diff-RDM-4841-add_indexes.xml
  src/main/resources/db/changelog/db.changelog-master.xml
  src/main/resources/db/migration/V1__baseline_migration.sql
  src/main/resources/liquibase.properties
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1419

#1414 LAU-495 Improve dm-store delete documents API performance
  src/main/java/uk/gov/hmcts/dm/controller/StoredDocumentDeleteController.java
  src/main/java/uk/gov/hmcts/dm/domain/StoredDocument.java
  src/main/java/uk/gov/hmcts/dm/repository/StoredDocumentRepository.java
  src/main/java/uk/gov/hmcts/dm/service/SearchService.java
  src/test/java/uk/gov/hmcts/dm/controller/StoredDocumentDeleteControllerTest.java
  src/test/java/uk/gov/hmcts/dm/controller/StoredDocumentDeleteControllerTests.java
  src/test/java/uk/gov/hmcts/dm/service/SearchServiceTests.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1414
