Repository hmcts/document-management-store-app, pull requests merged in 2022-12, with the labels that each got.

#1577 Removed unused media service resource
  infrastructure/main.tf
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1577

#1579 Revert "Removed unused media service resource"
  infrastructure/main.tf
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1579

#1564 Em 4832: Dm-store- Bump flyway-core from 8.5.13 to 9.8.2
  build.gradle
  src/main/java/uk/gov/hmcts/dm/data/migration/FlywayNoOpStrategy.java
  src/test/resources/application-local.yaml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1564

#1585 Removed unused media service resource
  infrastructure/main.tf
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1585
