Repository hmcts/document-management-store-app, pull requests merged in 2022-10, with the labels that each got.

#1478 Updated versions of pdf, azurerm & azuread
  build.gradle
  infrastructure/state.tf
Labels: ns:dm-store, prd:dm, no-changes, rel:dm-store-pr-1478

#1480 EM-4645 avoid CVE-2022-42003
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1480

#1487 Update swagger header parameters
  src/main/java/uk/gov/hmcts/dm/controller/DocumentContentVersionController.java
  src/main/java/uk/gov/hmcts/dm/controller/DocumentThumbnailController.java
  src/main/java/uk/gov/hmcts/dm/controller/StoredDocumentController.java
  src/main/java/uk/gov/hmcts/dm/controller/StoredDocumentDeleteController.java
  src/main/java/uk/gov/hmcts/dm/controller/StoredDocumentUpdateController.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1487

#1488 EM-3001 add pdf encryption validation
  src/main/java/uk/gov/hmcts/dm/service/FileContentVerifier.java
  src/test/java/uk/gov/hmcts/dm/service/FileContentVerifierTests.java
  src/test/resources/files/PasswordProtected.pdf
  src/test/resources/files/sample_encrypted.pdf
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1488

#1489 Added endpoint accessed log
  src/main/java/uk/gov/hmcts/dm/config/security/DmServiceRequestAuthorizer.java
  src/main/java/uk/gov/hmcts/dm/config/security/SpringSecurityConfiguration.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1489

#1504 Use postgres test db
  build.gradle
  src/test/resources/application-local.yaml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1504

#1509 EM-4708 clear-document-uri
  build.gradle
  src/main/java/uk/gov/hmcts/dm/service/BlobStorageDeleteService.java
  src/test/java/uk/gov/hmcts/dm/service/BlobStorageDeleteServiceTest.java
Labels: DO NOT MERGE, ns:dm-store, prd:dm, rel:dm-store-pr-1509
