Repository hmcts/document-management-store-app, pull requests merged in 2023-06, with the labels that each got.

#1789 Updating renovate config
  .github/renovate.json
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1789

#1760 use service-auth-provider-java-client
  build.gradle
  src/contractTest/java/uk/gov/hmcts/dm/controller/DocumentStoreProviderTest.java
  src/contractTest/java/uk/gov/hmcts/dm/controller/StoreDocumentControllerTestConfiguration.java
  src/main/java/uk/gov/hmcts/dm/config/AuditorAwareImpl.java
  src/main/java/uk/gov/hmcts/dm/config/security/DmServiceAuthFilter.java
  src/main/java/uk/gov/hmcts/dm/config/security/DmServiceRequestAuthorizer.java
  src/main/java/uk/gov/hmcts/dm/config/security/EmAuthCheckerConfiguration.java
  src/main/java/uk/gov/hmcts/dm/config/security/MethodSecurityConfig.java
  src/main/java/uk/gov/hmcts/dm/config/security/SpringSecurityConfiguration.java
  src/main/java/uk/gov/hmcts/dm/service/SecurityUtilService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/dm/componenttests/ComponentTestBase.java
  src/test/java/uk/gov/hmcts/dm/componenttests/ComponentTestConfiguration.java
  src/test/java/uk/gov/hmcts/dm/componenttests/TestConfiguration.java
  src/test/java/uk/gov/hmcts/dm/componenttests/backdoors/ServiceResolverBackdoor.java
  src/test/java/uk/gov/hmcts/dm/componenttests/backdoors/UserResolverBackdoor.java
  src/test/java/uk/gov/hmcts/dm/componenttests/sugar/RestActions.java
  src/test/java/uk/gov/hmcts/dm/controller/DocumentContentVersionControllerTest.java
  src/test/java/uk/gov/hmcts/dm/controller/DocumentThumbnailControllerTests.java
  src/test/java/uk/gov/hmcts/dm/controller/FolderControllerTests.java
  src/test/java/uk/gov/hmcts/dm/controller/HealthControllerTests.java
  src/test/java/uk/gov/hmcts/dm/controller/StoredDocumentAuditControllerTests.java
  src/test/java/uk/gov/hmcts/dm/controller/StoredDocumentControllerNoDeleteTests.java
  src/test/java/uk/gov/hmcts/dm/controller/StoredDocumentControllerTests.java
  src/test/java/uk/gov/hmcts/dm/controller/StoredDocumentDeleteControllerTests.java
  src/test/java/uk/gov/hmcts/dm/controller/StoredDocumentSearchControllerTests.java
  src/test/java/uk/gov/hmcts/dm/controller/StoredDocumentUpdateControllerTests.java
  src/test/java/uk/gov/hmcts/dm/endtoend/End2EndTestBase.java
  src/test/java/uk/gov/hmcts/dm/endtoend/SearchDocumentTest.java
  src/test/java/uk/gov/hmcts/dm/endtoend/VersionTest.java
  src/test/java/uk/gov/hmcts/dm/service/SecurityUtilServiceTests.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1760

#1802 Resolved CVE
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1802

#1813 Updated the ignore list
  src/main/java/uk/gov/hmcts/dm/config/security/SpringSecurityConfiguration.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1813

#1821 Resolved CVE
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1821
