Repository hmcts/document-management-store-app, pull requests merged in 2023-11, with the labels that each got.

#2021 EM-5644 fix builds
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2021

#2028 EM-5649 bump java and app insight jar
  Dockerfile
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2028

#2016 EM-5266 add delete orphan doc task
  src/main/java/uk/gov/hmcts/dm/config/batch/OrphanDocumentDeletionBatchConfig.java
  src/main/java/uk/gov/hmcts/dm/config/batch/OrphanDocumentDeletionTask.java
  src/main/java/uk/gov/hmcts/dm/config/batch/OrphanDocumentDeletionTasklet.java
  src/test/java/uk/gov/hmcts/dm/config/batch/OrphanDocumentDeletionTaskTest.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2016, destroy

#2032 EM-5266 add Shed lock provider
  src/main/java/uk/gov/hmcts/dm/config/batch/ShedLockConfig.java
  src/main/resources/application.yaml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2032

#2034 EM-5266 add transactional
  src/main/java/uk/gov/hmcts/dm/config/batch/OrphanDocumentDeletionTask.java
  src/test/java/uk/gov/hmcts/dm/config/batch/OrphanDocumentDeletionTaskTest.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2034

#2027 add m4a to whitelist
  src/contractTest/resources/application.yaml
  src/functionalTest/java/uk/gov/hmcts/dm/functional/MultiMediaUploadIT.java
  src/functionalTest/resources/files/m4a.m4a
  src/main/resources/application.yaml
Labels: ns:dm-store, prd:dm, enable_keep_helm, rel:dm-store-pr-2027

#2037 EM-5266 Transactional delete
  src/main/java/uk/gov/hmcts/dm/config/batch/OrphanDocumentDeletionTask.java
  src/main/java/uk/gov/hmcts/dm/service/BlobStorageDeleteService.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2037

#2050 Revert "Update versions.jackson to v2.16.0 (#2047)" and suppress CVE-2023-36052
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2050

#2054 EM-5653 remove keep
  acb.tpl.yaml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2054

#2048 Added force_user_permissions_trigger
  infrastructure/main.tf
Labels: ns:dm-store, prd:dm, destroy, rel:dm-store-pr-2048

#2058 Updated v15 DB config
  charts/dm-store/Chart.yaml
  charts/dm-store/values.yaml
  infrastructure/main.tf
Labels: ns:dm-store, prd:dm, Do Not Merge, destroy, rel:dm-store-pr-2058

#2064 EM-5686 extend suppression CVE-2023-36052
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2064
