Repository hmcts/document-management-store-app, pull requests merged in 2023-01, with the labels that each got.

#1598 EM-4912 suppress vulnerability
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, no-changes, rel:dm-store-pr-1598

#1600 EM-4910: Added missing configuration to fix delete functional tests
  docker-compose-dev.yml
  src/functionalTest/java/uk/gov/hmcts/dm/functional/BaseIT.java
  src/functionalTest/java/uk/gov/hmcts/dm/functional/MultiMediaUploadIT.java
  src/functionalTest/resources/application.yml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1600

#1515 EM-4533 tune delete job config
  charts/dm-store/values.aat.template.yaml
  charts/dm-store/values.yaml
  src/contractTest/resources/application.yaml
  src/main/java/uk/gov/hmcts/dm/config/batch/BatchConfiguration.java
  src/main/java/uk/gov/hmcts/dm/service/BlobStorageDeleteService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/dm/service/BlobStorageDeleteServiceTest.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1515

#1609 Suppress CVE
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1609

#1611 EM-4943 suppress vulnerability
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1611

#1613 Fix pact provider version
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1613

#1632 EM-4906 add log
  src/main/java/uk/gov/hmcts/dm/service/StoredDocumentService.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1632

#1635 EM-4906 add log for hasPermission
  src/main/java/uk/gov/hmcts/dm/security/domain/DomainPermissionEvaluator.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1635

#1637 EM-4765 add log for broken pipe
  src/main/java/uk/gov/hmcts/dm/controller/StoredDocumentController.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1637

#1639 EM-4765 increase test coverage
  src/main/java/uk/gov/hmcts/dm/controller/StoredDocumentController.java
  src/test/java/uk/gov/hmcts/dm/componenttests/ComponentTestBase.java
  src/test/java/uk/gov/hmcts/dm/controller/StoredDocumentControllerTests.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1639

#1642 EM-4765 x-azure-ref log
  src/main/java/uk/gov/hmcts/dm/controller/StoredDocumentController.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1642

#1641 EM-5015 bump-hmcts.java
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1641

#1645 EM-5019 fix-pipeline
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1645
