Repository hmcts/document-management-store-app, pull requests merged in 2023-03, with the labels that each got.

#1687 Lower azure-storage-blob version
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1687

#1694 Updated CVE list
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1694

#1712 Resolve CVE-2022-1471
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1712
