Repository hmcts/document-management-store-app, pull requests merged in 2023-10, with the labels that each got.

#1975 Suppress CVE-2023-4586
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1975

#1990 remove appinsight custom classes
  build.gradle
  src/main/java/uk/gov/hmcts/dm/appinsights/AppInsightsEventRepository.java
  src/main/java/uk/gov/hmcts/dm/appinsights/AppInsightsEvents.java
  src/main/java/uk/gov/hmcts/dm/appinsights/EventRepository.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1990

#1992 EM-5616 CVE-2023-5072-vulnerability
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1992

#2002 EM-5505 reduce logs
  lib/applicationinsights.json
  src/main/java/uk/gov/hmcts/dm/security/domain/DomainPermissionEvaluator.java
Labels: ns:dm-store, prd:dm, add-or-update, rel:dm-store-pr-2002
