Repository hmcts/document-management-store-app, pull requests merged in 2023-04, with the labels that each got.

#1724 Updated CVE list
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1724

#1730 EM-5186 remove security.sh
  security.sh
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1730

#1731 Em-5186 suppress sec scan vulnerability
  audit.json
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1731

#1735 EM-5196 suppress
  audit.json
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1735

#1738 EM-5196 create functional-output folder
  audit.json
  functional-output/zap.reports
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1738

#1742 Welcome endpoint to return JSON response
  src/main/java/uk/gov/hmcts/dm/controller/WelcomeController.java
  src/smokeTest/java/uk/gov/hmcts/dm/smoke/SmokeTest.java
  src/test/java/uk/gov/hmcts/dm/controller/WelcomeControllerTest.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1742
