Repository hmcts/document-management-store-app, pull requests merged in 2023-09, with the labels that each got.

#1913 Resolve CVE-2023-41080
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1913

#1912 Em 2764 api standard improvement
  src/contractTest/java/uk/gov/hmcts/dm/controller/StoreDocumentControllerTestConfiguration.java
  src/functionalTest/java/uk/gov/hmcts/dm/functional/BaseIT.java
  src/functionalTest/java/uk/gov/hmcts/dm/functional/CreateDocumentIT.java
  src/functionalTest/java/uk/gov/hmcts/dm/functional/ReadThumbnailIT.java
  src/functionalTest/java/uk/gov/hmcts/dm/functional/V1MediaTypes.java
  src/functionalTest/resources/files/ThumbnailJPG.jpg
  src/functionalTest/resources/files/ThumbnailNPad.jpg
  src/functionalTest/resources/files/thumbnailBMP.jpg
  src/functionalTest/resources/files/thumbnailGIF.jpg
  src/functionalTest/resources/files/thumbnailPDF.jpg
  src/main/java/uk/gov/hmcts/dm/config/AddMediaTypeSupportConfiguration.java
  src/main/java/uk/gov/hmcts/dm/config/ToggleConfiguration.java
  src/main/java/uk/gov/hmcts/dm/config/V1MediaType.java
  src/main/java/uk/gov/hmcts/dm/config/security/SpringSecurityConfiguration.java
  src/main/java/uk/gov/hmcts/dm/config/thumbnail/ThumbnailConfig.java
  src/main/java/uk/gov/hmcts/dm/controller/DocumentThumbnailController.java
  src/main/java/uk/gov/hmcts/dm/controller/FolderController.java
  src/main/java/uk/gov/hmcts/dm/exception/CantCreateThumbnailException.java
  src/main/java/uk/gov/hmcts/dm/hateos/DocumentContentVersionHalResource.java
  src/main/java/uk/gov/hmcts/dm/hateos/FolderHalResource.java
  src/main/java/uk/gov/hmcts/dm/hateos/StoredDocumentHalResource.java
  src/main/java/uk/gov/hmcts/dm/repository/FolderRepository.java
  src/main/java/uk/gov/hmcts/dm/service/AuditedDocumentContentVersionOperationsService.java
  src/main/java/uk/gov/hmcts/dm/service/FolderService.java
  src/main/java/uk/gov/hmcts/dm/service/StoredDocumentService.java
  src/main/java/uk/gov/hmcts/dm/service/thumbnail/AbstractFileSpecificThumbnailCreator.java
  src/main/java/uk/gov/hmcts/dm/service/thumbnail/BufferedImageResizer.java
  src/main/java/uk/gov/hmcts/dm/service/thumbnail/DocumentThumbnailService.java
  src/main/java/uk/gov/hmcts/dm/service/thumbnail/ImageThumbnailCreator.java
  src/main/java/uk/gov/hmcts/dm/service/thumbnail/PdfThumbnailCreator.java
  src/main/java/uk/gov/hmcts/dm/service/thumbnail/ThumbnailCreator.java
  src/main/java/uk/gov/hmcts/dm/service/thumbnail/ThumbnailFormats.java
  src/main/java/uk/gov/hmcts/dm/service/thumbnail/ThumbnailWidths.java
  src/main/java/uk/gov/hmcts/dm/service/thumbnail/UnsupportedThumbnailCreator.java
  src/smokeTest/java/uk/gov/hmcts/dm/smoke/MappingUrlIT.java
  src/smokeTest/java/uk/gov/hmcts/dm/smoke/utilities/V1MediaTypes.java
  src/test/java/uk/gov/hmcts/dm/componenttests/ComponentTestBase.java
  src/test/java/uk/gov/hmcts/dm/componenttests/TestUtil.java
  src/test/java/uk/gov/hmcts/dm/controller/DocumentContentVersionControllerTest.java
  src/test/java/uk/gov/hmcts/dm/controller/DocumentThumbnailControllerTests.java
  src/test/java/uk/gov/hmcts/dm/controller/FolderControllerTests.java
  src/test/java/uk/gov/hmcts/dm/controller/StoredDocumentControllerNoDeleteTests.java
  src/test/java/uk/gov/hmcts/dm/controller/StoredDocumentControllerTests.java
  src/test/java/uk/gov/hmcts/dm/endtoend/Helper.java
  src/test/java/uk/gov/hmcts/dm/endtoend/ThumbnailTest.java
  src/test/java/uk/gov/hmcts/dm/endtoend/VersionTest.java
  src/test/java/uk/gov/hmcts/dm/hateos/DocumentContentVersionHalResourceTest.java
  src/test/java/uk/gov/hmcts/dm/service/AuditedDocumentContentVersionOperationsServiceTests.java
  src/test/java/uk/gov/hmcts/dm/service/FolderServiceTests.java
  src/test/java/uk/gov/hmcts/dm/service/StoredDocumentServiceTests.java
  src/test/java/uk/gov/hmcts/dm/service/thumbnail/DocumentThumbnailServiceTest.java
  src/test/java/uk/gov/hmcts/dm/service/thumbnail/ImageThumbnailCreatorTest.java
  src/test/java/uk/gov/hmcts/dm/service/thumbnail/PdfThumbnailCreatorTest.java
  src/test/java/uk/gov/hmcts/dm/service/thumbnail/UnsupportedThumbnailCreatorTest.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1912

#1917 Removing pdfbox dependency
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1917

#1920 Em 2764 api standard improvement solve deprecations
  src/main/java/uk/gov/hmcts/dm/config/batch/BatchConfiguration.java
  src/main/java/uk/gov/hmcts/dm/config/batch/MetadataMigrationConfiguration.java
  src/main/java/uk/gov/hmcts/dm/config/batch/OrphanDocumentDeletionBatchConfig.java
  src/main/java/uk/gov/hmcts/dm/domain/DocumentContentVersion.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1920

#1932 Update Renovate config
  .github/renovate.json
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1932

#1938 Em 5551 update renovate config
  .github/dependabot.yml
  .github/stale.yml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1938

#1940 Em 5551 update renovate config
  .github/renovate.json
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1940

#1944 Em 5551 update renovate config
  .github/renovate.json
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1944

#1955 EM-5569 Update dependency-check-suppressions.xml
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1955
