Repository hmcts/document-management-store-app, pull requests merged in 2023-07, with the labels that each got.

#1827 Resolved CVE
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1827

#1820 EM-5114 get ready for spring-3
  src/main/java/uk/gov/hmcts/dm/dialect/ByteWrappingBlobType.java
  src/main/java/uk/gov/hmcts/dm/dialect/CustomPostgresSqlDialect.java
  src/main/java/uk/gov/hmcts/dm/dialect/PassThroughBlob.java
  src/main/java/uk/gov/hmcts/dm/domain/DocumentContent.java
  src/main/java/uk/gov/hmcts/dm/domain/DocumentContentVersion.java
  src/test/java/uk/gov/hmcts/dm/dialect/ByteWrappingBlobTypeTests.java
  src/test/java/uk/gov/hmcts/dm/dialect/CustomH2Dialect.java
  src/test/java/uk/gov/hmcts/dm/dialect/CustomPostgresSqlDialectTests.java
  src/test/java/uk/gov/hmcts/dm/dialect/PassThroughBlobTests.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1820

#1834 Excluded health check
  build.gradle
  src/main/java/uk/gov/hmcts/dm/config/security/DmServiceAuthFilter.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1834

#1838 Excluded health check
  src/main/java/uk/gov/hmcts/dm/config/security/DmServiceAuthFilter.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1838

#1837 deregister filter
  src/main/java/uk/gov/hmcts/dm/config/security/DmServiceAuthFilter.java
  src/main/java/uk/gov/hmcts/dm/config/security/EmAuthCheckerConfiguration.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1837

#1845 Updated Hikari connection-timeout
  charts/dm-store/Chart.yaml
  charts/dm-store/values.yaml
  src/main/resources/application.yaml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1845

#1866 Upgrade Gradle version 8.
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1866

#1868 Resolved CVE & removed redundant CVE
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1868
