Repository hmcts/document-management-store-app, pull requests merged in 2023-02, with the labels that each got.

#1655 Updated terraform version
  infrastructure/.terraform-version
Labels: ns:dm-store, prd:dm, no-changes, rel:dm-store-pr-1655

#1659 Bump com.azure:azure-storage-blob from 12.20.2 to 12.20.3
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1659

#1684 Suppress CVE
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-1684
