Repository hmcts/document-management-store-app, pull requests merged in 2024-01, with the labels that each got.

#2117 Only create container if it does not exist
  src/main/java/uk/gov/hmcts/dm/config/azure/AzureStorageConfiguration.java
  src/main/java/uk/gov/hmcts/dm/config/azure/MetaDataAzureStorageConfiguration.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2117

#2132 add graceful shutdown
  src/main/resources/application.yaml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2132

#2134 Update dependency-check-suppressions.xml extend CVE
  config/owasp/dependency-check-suppressions.xml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2134

#2111 update hard delete job
  charts/dm-store/Chart.yaml
  charts/dm-store/values.yaml
  src/main/java/uk/gov/hmcts/dm/config/batch/BatchConfiguration.java
  src/main/java/uk/gov/hmcts/dm/config/batch/RemoveSpringBatchHistoryTasklet.java
  src/main/java/uk/gov/hmcts/dm/service/BlobStorageDeleteService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/dm/service/BlobStorageDeleteServiceTest.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2111

#2139 EM-5801 - bump pitest plugin
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2139
