Repository hmcts/document-management-store-app, pull requests merged in 2024-11, with the labels that each got.

#2454 EM-6297: enable file password check
  charts/dm-store/Chart.yaml
  charts/dm-store/values.yaml
  src/main/resources/application.yaml
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2454

#2488 update serenity to 4.2.9
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/dm/functional/BaseIT.java
  src/functionalTest/java/uk/gov/hmcts/dm/functional/CreateDocumentIT.java
  src/functionalTest/java/uk/gov/hmcts/dm/functional/MetadataMigrationIT.java
  src/functionalTest/java/uk/gov/hmcts/dm/functional/MultiMediaUploadIT.java
  src/smokeTest/java/uk/gov/hmcts/dm/smoke/BaseIT.java
  src/smokeTest/java/uk/gov/hmcts/dm/smoke/MappingUrlIT.java
  src/smokeTest/java/uk/gov/hmcts/dm/smoke/SmokeTest.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2488

#2489 update pact to 4.6.15
  Jenkinsfile_CNP
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2489
