Repository hmcts/document-management-store-app, pull requests merged in 2025-01, with the labels that each got.

#2521 EM-6347 junit5 upgrade part-1
  src/test/java/uk/gov/hmcts/dm/actuate/health/WebCheckerTest.java
  src/test/java/uk/gov/hmcts/dm/actuate/info/DmBuildInfoTest.java
  src/test/java/uk/gov/hmcts/dm/componenttests/ComponentTestBase.java
  src/test/java/uk/gov/hmcts/dm/controller/DocumentContentVersionControllerTest.java
  src/test/java/uk/gov/hmcts/dm/controller/StoredDocumentAuditControllerTests.java
  src/test/java/uk/gov/hmcts/dm/controller/StoredDocumentControllerNoDeleteTests.java
  src/test/java/uk/gov/hmcts/dm/controller/StoredDocumentControllerTests.java
  src/test/java/uk/gov/hmcts/dm/controller/StoredDocumentDeleteControllerTests.java
  src/test/java/uk/gov/hmcts/dm/controller/StoredDocumentSearchControllerTests.java
  src/test/java/uk/gov/hmcts/dm/controller/StoredDocumentUpdateControllerTests.java
  src/test/java/uk/gov/hmcts/dm/controller/WelcomeControllerTest.java
  src/test/java/uk/gov/hmcts/dm/controller/testing/TestControllerTest.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2521

#2522 EM-6347 junit5 upgrade part-3
  src/test/java/uk/gov/hmcts/dm/security/MultipartFileWhiteListValidatorTest.java
  src/test/java/uk/gov/hmcts/dm/security/MultipartFileWhiteListValidatorTests.java
  src/test/java/uk/gov/hmcts/dm/security/PermissionEvaluatorImplTests.java
  src/test/java/uk/gov/hmcts/dm/security/domain/DomainPermissionEvaluatorTests.java
  src/test/java/uk/gov/hmcts/dm/utils/StringUtilsTests.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2522

#2520 EM-6347 junit5 upgrade part-2
  src/test/java/uk/gov/hmcts/dm/endtoend/AuditTest.java
  src/test/java/uk/gov/hmcts/dm/endtoend/End2EndTestBase.java
  src/test/java/uk/gov/hmcts/dm/endtoend/PermissionTest.java
  src/test/java/uk/gov/hmcts/dm/endtoend/SearchDocumentTest.java
  src/test/java/uk/gov/hmcts/dm/endtoend/UploadDocumentTest.java
  src/test/java/uk/gov/hmcts/dm/endtoend/VersionTest.java
  src/test/java/uk/gov/hmcts/dm/errorhandler/ApiErrorControllerTest.java
  src/test/java/uk/gov/hmcts/dm/errorhandler/ExceptionStatusCodeAndMessageResolverTest.java
  src/test/java/uk/gov/hmcts/dm/hateos/DocumentContentVersionHalResourceTest.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2520

#2524 EM-6347 junit5 upgrade part-4
  src/test/java/uk/gov/hmcts/dm/service/AuditEntryServiceTests.java
  src/test/java/uk/gov/hmcts/dm/service/AuditedDocumentContentVersionOperationsServiceTests.java
  src/test/java/uk/gov/hmcts/dm/service/AuditedStoredDocumentOperationsServiceTests.java
  src/test/java/uk/gov/hmcts/dm/service/BlobStorageDeleteServiceTest.java
  src/test/java/uk/gov/hmcts/dm/service/BlobStorageReadServiceTest.java
  src/test/java/uk/gov/hmcts/dm/service/BlobStorageWriteServiceTest.java
  src/test/java/uk/gov/hmcts/dm/service/DocumentContentVersionServiceTests.java
  src/test/java/uk/gov/hmcts/dm/service/FileContentVerifierTests.java
  src/test/java/uk/gov/hmcts/dm/service/FileSizeVerifierTest.java
  src/test/java/uk/gov/hmcts/dm/service/SearchServiceTests.java
  src/test/java/uk/gov/hmcts/dm/service/SecurityUtilServiceTests.java
  src/test/java/uk/gov/hmcts/dm/service/StoredDocumentServiceTests.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2524

#2526 EM-6347 junit5 upgrade part-6 smoke tests
  build.gradle
  src/smokeTest/java/uk/gov/hmcts/dm/smoke/MappingUrlIT.java
  src/smokeTest/java/uk/gov/hmcts/dm/smoke/SmokeTest.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2526

#2525 Em 6347 junit5 upgrade 5
  src/test/java/uk/gov/hmcts/dm/service/AuditedStoredDocumentOperationsServiceTests.java
  src/test/java/uk/gov/hmcts/dm/service/FileSizeVerifierTest.java
  src/test/java/uk/gov/hmcts/dm/service/PasswordVerifierTest.java
  src/test/java/uk/gov/hmcts/dm/service/batch/AuditedStoredDocumentBatchOperationsServiceTests.java
  src/test/java/uk/gov/hmcts/dm/utils/StringUtilsTests.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2525

#2533 fix pitest, junit 5 upgrade EM-6347
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2533

#2527 EM-6347 junit5 upgrade part-7 functional tests
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/dm/functional/AddContentVersionIT.java
  src/functionalTest/java/uk/gov/hmcts/dm/functional/AuthTokenProvider.java
  src/functionalTest/java/uk/gov/hmcts/dm/functional/BaseIT.java
  src/functionalTest/java/uk/gov/hmcts/dm/functional/CreateDocumentIT.java
  src/functionalTest/java/uk/gov/hmcts/dm/functional/DeleteDocumentIT.java
  src/functionalTest/java/uk/gov/hmcts/dm/functional/DeleteDocumentsIT.java
  src/functionalTest/java/uk/gov/hmcts/dm/functional/ErrorPageIT.java
  src/functionalTest/java/uk/gov/hmcts/dm/functional/LargeMultiMediaUploadIT.java
  src/functionalTest/java/uk/gov/hmcts/dm/functional/MetadataMigrationIT.java
  src/functionalTest/java/uk/gov/hmcts/dm/functional/MultiMediaUploadIT.java
  src/functionalTest/java/uk/gov/hmcts/dm/functional/ReadContentVersionIT.java
  src/functionalTest/java/uk/gov/hmcts/dm/functional/ReadDocumentIT.java
  src/functionalTest/java/uk/gov/hmcts/dm/functional/SearchDocumentIT.java
  src/functionalTest/java/uk/gov/hmcts/dm/functional/UpdateDocumentIT.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2527

#2536 EM-6347 remove junit 4 dependency
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2536

#2538 EM-6347 remove junit4 elements
  src/functionalTest/java/uk/gov/hmcts/dm/functional/LargeMultiMediaUploadIT.java
  src/test/java/uk/gov/hmcts/dm/controller/WelcomeControllerTest.java
  src/test/java/uk/gov/hmcts/dm/errorhandler/ExceptionStatusCodeAndMessageResolverTest.java
  src/test/java/uk/gov/hmcts/dm/security/MultipartFileWhiteListValidatorTest.java
  src/test/java/uk/gov/hmcts/dm/security/PermissionEvaluatorImplTests.java
  src/test/java/uk/gov/hmcts/dm/service/StoredDocumentServiceTests.java
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2538

#2541 EM-6379 remove DirtiesContext ro speed up pitests
  src/test/java/uk/gov/hmcts/dm/componenttests/ComponentTestBase.java
Labels: ns:dm-store, prd:dm

#2548 upgrade em-test-helper to 2.1.1
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/dm/functional/BaseIT.java
Labels: ns:dm-store, prd:dm

#2551 Removed redundant lines of code
  src/main/java/uk/gov/hmcts/dm/config/batch/BatchConfiguration.java
Labels: ns:dm-store, prd:dm

#2566 remove MockBean and use MockitoBean
  Jenkinsfile_CNP
  src/contractTest/java/uk/gov/hmcts/dm/controller/DocumentStoreProviderTest.java
  src/contractTest/java/uk/gov/hmcts/dm/controller/StoreDocumentControllerTestConfiguration.java
Labels: ns:dm-store, prd:dm

#2564 Removed redundant class
  src/main/java/uk/gov/hmcts/dm/service/batch/DeleteAllExpiredStoredDocumentTasklet.java
Labels: ns:dm-store, prd:dm
