Repository hmcts/document-management-store-app, pull requests merged in 2025-08, with the labels that each got.

#2804 EM-6466 add pact test for POST version endpoint
  src/contractTest/java/uk/gov/hmcts/dm/controller/consumer/DocumentContentVersionControllerConsumerTest.java
  src/contractTest/java/uk/gov/hmcts/dm/controller/provider/DocumentContentVersionControllerProviderTest.java
  src/contractTest/java/uk/gov/hmcts/dm/controller/provider/StoredDocumentAuditControllerProviderTest.java
  src/contractTest/resources/test-files/sample.pdf
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2804

#2813 update output location
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2813

#2814 add buildscript
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2814

#2833 update em-test-helper
  build.gradle
Labels: ns:dm-store, prd:dm, rel:dm-store-pr-2833
